# Generated by Django 5.2.1 on 2025-05-27 04:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customuser_age_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись на услугу', 'verbose_name_plural': 'Записи на услуги'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_group',
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Дополнительные пожелания'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='preferred_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Предпочтительная дата'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Продолжительность (минут)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='servicebooking',
            table='service_bookings',
        ),
    ]
