/**
 * Declare action types for reducers
 */
export const GENRES_LOADING = 'GENRES_LOADING';
export const GENRES_FAILED = 'GENRES_FAILED';
export const ADD_GENRES = 'ADD_GENRES';

export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_FAILED = 'POSTS_FAILED';
export const ADD_POSTS = 'ADD_POSTS';

export const FEATUREDPOSTS_LOADING = 'FEATUREDPOSTS_LOADING';
export const FEATUREDPOSTS_FAILED = 'FEATUREDPOSTS_FAILED';
export const ADD_FEATUREDPOSTS = 'ADD_FEATUREDPOSTS';

export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const ADD_COMMENTS = 'ADD_COMMENTS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USER_DATA_LOADING = 'USER_DATA_LOADING';
export const USER_DATA_FAILED = 'USER_DATA_FAILED';
export const ADD_USER_DATA = 'ADD_USER_DATA';

export const PROFILE_IMAGES_LOADING = 'PROFILE_IMAGES_LOADING';
export const PROFILE_IMAGES_FAILED = 'PROFILE_IMAGES_FAILED';
export const ADD_PROFILE_IMAGES = 'ADD_PROFILE_IMAGES';