# Generated by Django 3.1 on 2022-08-28 14:00

from django.db import migrations, models
import django.db.models.deletion
import genres.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile_image', serialize=False, to='auth.user')),
                ('profile_image', models.ImageField(upload_to=genres.models.get_file_path)),
            ],
        ),
    ]
