# Generated by Django 3.1 on 2022-08-28 14:00

from django.db import migrations, models
import genres.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('show_menu_list', models.CharField(choices=[('YES', 'Show in menu list'), ('NO', 'Not show in menu list')], default='NO', max_length=3)),
                ('image_genre', models.ImageField(blank=True, null=True, upload_to=genres.models.get_file_path)),
            ],
        ),
    ]
